name = 'monitor'
link = "https://www.emag.ro/monitoare-lcd-led/filter/rezolutie-optima-f6126,qhd-qhd-v31145/tehnologie-display-f6150,ips-v22247/rata-de-refresh-maximala-f6605,144-hz-v24571/rata-de-refresh-maximala-f6605,165-hz-v24576/sort-priceasc/c?ref=delete_filter_left_bar"
root = '//div[@class="card-item card-standard js-product-data"]'
next-page = '//a[contains(@class, "js-next-page")]/@href'
type = 'product-listing'
driver = 'playwright'
price-limit = 1600
threshold = 30

[fields]
title = ".//a[contains(@class, 'card-v2-title')]/text()"
stoc = ".//div[contains(@class, 'card-estimate-placeholder')]/div/text()"
price = './/p[@class="product-new-price"]/text()'
href = ".//a[contains(@class, 'card-v2-title')]/@href"